accounts/urls.py
from . import views
from django.urls import path


app_name= 'accounts'

urlpatterns = [
    
    path('login/', views.login_view , name='login'),
    path('logout', views.logout_view , name='logout'),
    path('signup/' , views.signup_view , name='signup'),
    path('password_reset', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),


    
    
]    

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed
import website.views as websiteviews

app_name='blog'

urlpatterns = [
 
    #path('url', 'def_views', 'name') 
    path('', blog_view,name='index'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>' ,blog_view, name='category'),
    path('author/<str:author_username>',blog_view, name='author'),
    path('search/',blog_search ,name='search'),
    path('tag/<str:tag_name>', blog_view,name='tag'),
    path('rss/feed/', LatestEntriesFeed() ) ,
    path('test', test , name='test'),
    
] 

mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
import website.views as websiteviews


sitemaps={
    'static':StaticViewSitemap ,
    'blog': BlogSitemap,
     
} 


urlpatterns = [
    #path('url', 'def_views', 'name') 
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt',include('robots.urls'),),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    

 
    #App
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] 
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms

from django.contrib.auth.forms import (PasswordChangeForm,
                                       ReadOnlyPasswordHashField)
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import (PasswordChangeForm,
                                       ReadOnlyPasswordHashField)
from django.core.exceptions import ValidationError
# from .models import User
from django.core import validators




class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']
        
class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False)
    
    


class ChangeEmailForm(forms.Form):
      email = forms.EmailField(
      widget=forms.TextInput(attrs={"class":"form-control","placeholder": "ایمیل خود را وارد کنید"}))

        
class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput({'placeholder': "گذرواژه فعلی", 'id': "old_password"}))
    new_password1 = forms.CharField(widget=forms.PasswordInput({'placeholder': "گذرواژه جدید", 'id': "new_password1"}))
    new_password2 = forms.CharField(widget=forms.PasswordInput({'placeholder': "تکرار گذرواژه", 'id': "new_password2"}))

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise ValidationError("گذرواژه فعلی تان اشتباه وارد شد. لطفا دوباره تلاش کنید")
        return old_password


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'is_active', 'is_superuser','is_staff')        

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth
# from django.contrib.auth import  get_user_model
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)

from django.urls import reverse_lazy
from .forms import *

from django.core.mail import send_mail
from django.conf import settings

# Create your views here.


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            userinput = request.POST['username']
            try:
                username = User.objects.get(email=userinput).username
            except User.DoesNotExist:
                username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                messages.add_message(request,messages.SUCCESS,'Login was successful')
                return redirect('/')
            else:
                 messages.add_message(request,messages.ERROR,'TheDesiredPersonWasNotFound')
        return render(request, "accounts/login.html")
    else:
          return redirect('/')

@login_required
def logout_view(request):
    #  if request.user.is_authenticated:
          logout(request)
          return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
              form=SignUpForm(request.POST)
              if form.is_valid():
                form.save()
                return redirect('/')
        # form=UserCreationForm()
        form=SignUpForm()
        context={'form':form}
        return render(request,'accounts/signup.html',context)
    else:
          return redirect('/')
    
 
    
    
    
    
class PasswordReset(PasswordResetView):
    template_name="accounts/password_reset_form.html"
    success_url=reverse_lazy("accounts:password_reset_done")

class PasswordResetDone(PasswordResetDoneView):
    template_name="accounts/password_reset_done.html"
    success_url=reverse_lazy("accounts:password_reset_confirm")

class PasswordResetConfirm(PasswordResetConfirmView):
    template_name="accounts/password_reset_confirm.html"
    success_url=reverse_lazy("accounts:password_reset_complete")

class PasswordResetComplete(PasswordResetCompleteView):
    template_name="accounts/password_reset_complete.html"    

templates/accounts/login.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>login </title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css'%}" rel="stylesheet">
  </head>
  <body class="text-center">
     
    <form class="form-signin" method="post" action="{%url 'accounts:login'%}">
        {% csrf_token %}
         <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-center mt-4">
   {% if messages %}
       {% for message in messages %}
          <div class=class="h3 mb-3 font-weight-normal">
             <div class="col-4 text-center">
                 <div class="alert alert-{{message.tags}}">
         <h2> {{ message }}</h2>
                 </div>
              </div>
           </div>
        {% endfor %}
   {% endif%}
       </div>
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      
      <h1 class="h3 mb-3 font-weight-normal">Please log in</h1>
      <label for="inputEmail" class="sr-only">username</label>
      <input type="text" name="username" class="form-control" placeholder="Email or Username" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">log in</button>
       <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-center mt-4">
           <a href="{%url 'accounts:signup'%}" class="link-secondary text-decoration-none">Create new account</a>
         </div> 
          <div>
             <a href="{% url 'accounts:password_reset'%}" class="link-secondary text-decoration-none">  Forgot password</a>  
          </div>    

 
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

templates/accounts/password_reset_complete.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>done</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/logins/login-10/assets/css/login-10.css"> -->
</head>
<body>
              
<!-- Login 10 - Bootstrap Brain Component -->
<section class="bg-light py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
          <div class="mb-5">
            <div class="text-center mb-4">
              <a href="#!">
                <!-- <img src="./assets/img/bsb-logo.svg" alt="BootstrapBrain Logo" width="175" height="57"> -->
              </a>
            </div>
            <h4 class="text-center mb-4">Welcome to page password reset complete</h4>
          </div>
          <div class="card border border-light-subtle rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <form method="post" action="{%url 'accounts:password_reset_done'%}">
                {%csrf_token%}
                <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                  </div>
                  <p>the password has been changed.</p>
                  <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-lg">Return to log in</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>

templates/accounts/password_reset_confirm.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset password confirm</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/logins/login-10/assets/css/login-10.css"> -->
</head>
<body>
              
<!-- Login 10 - Bootstrap Brain Component -->
<section class="bg-light py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
          <div class="mb-5">
            <div class="text-center mb-4">
              <a href="#!">
                <!-- <img src="./assets/img/bsb-logo.svg" alt="BootstrapBrain Logo" width="175" height="57"> -->
              </a>
            </div>
            <h4 class="text-center mb-4">Welcome to page password  reset confirm </h4>
            <div class="text-center">
              <!-- <a href="#!" class="btn bsb-btn-2xl btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                  <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
                </svg>
                <span class="ms-2 fs-6">Sign up with Google</span>
              </a> -->
            </div>
          </div>
          <div class="card border border-light-subtle rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <form method="post" action="#">
                {%csrf_token%}
                <!-- <p class="text-center mb-4">Or Sign up using email</p> -->
                <div class="row gy-3 overflow-hidden">
                  <!-- {{form.as_p}} -->
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      <input type="password" class="form-control" name="password1" value="" placeholder="Password" required>
                      <label for="password" class="form-label">Password</label>
                    </div>
                   <div class="col-12">
                        <div class="form-floating mb-3">
                          <input type="password" class="form-control" name="password2" value="" placeholder="Confirm Password" required>
                          <label for="password" class="form-label">Confirm Password</label>
                        </div>
                  </div>
                  <div class="col-12">
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                      <button class="btn btn-primary btn-lg" type="submit">change password</button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-center mt-4">
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html

templates/accounts/password_reset_done.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>done</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/logins/login-10/assets/css/login-10.css"> -->
</head>
<body>
              
<!-- Login 10 - Bootstrap Brain Component -->
<section class="bg-light py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
          <div class="mb-5">
            <div class="text-center mb-4">
              <a href="#!">
                <!-- <img src="./assets/img/bsb-logo.svg" alt="BootstrapBrain Logo" width="175" height="57"> -->
              </a>
            </div>
            <h4 class="text-center mb-4">Welcome to page password reset done</h4>
            <h4 class="text-center mb-4">Email successfully sent to user</h4>
          </div>
          <div class="card border border-light-subtle rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <form method="post" action="{%url 'accounts:password_reset_done'%}">
                {%csrf_token%}
                <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                  </div>
                  <p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.</p>
                  <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-lg">Return to log in</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>

templates/accounts/password_reset_email.html
<p>Hi</p>

        <p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>

        <p>Please click the following link to reset your password:</p>

        {{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}

        <p>Thanks</p>
        <p>Todo App Team</p>
 

templates/accounts/password_reset_form.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset password</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/logins/login-10/assets/css/login-10.css"> -->
   </head>
  <body>
              
<!-- Login 10 - Bootstrap Brain Component -->
<section class="bg-light py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
          <div class="mb-5">
            <div class="text-center mb-4">
              <a href="#!">
                <!-- <img src="./assets/img/bsb-logo.svg" alt="BootstrapBrain Logo" width="175" height="57"> -->
              </a>
            </div>
            <h4 class="text-center mb-4">Welcome to page reset password</h4>
            <div class="text-center">
              <!-- <a href="#!" class="btn bsb-btn-2xl btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                  <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
                </svg>
                <span class="ms-2 fs-6">forget psswordwith Google</span>
              </a> -->
            </div>
          </div>
          <div class="card border border-light-subtle rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <form method="post" action="{%url 'accounts:password_reset'%}">
                {%csrf_token%}
                <!-- <p class="text-center mb-4">Or forget psswordusing email</p> -->
                <div class="row gy-3 overflow-hidden">
                  <!-- {{form.as_p}} -->
                  <div class="col-12">
                  </div>
                  <div class="col-12">
                        <h3 class="card-title">Reset your password</h3>
                        <p>Enter your email address and we will send you a link to reset your password.</p>
                    <div class="form-floating mb-3"></div>
                      <input type="email" class="form-control" name="email" placeholder="Email" required autofocus >
                      <!-- <label for="email" class="form-label">Email</label> -->
                    </div>
                  <div class="col-12">
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                      <button class="btn btn-primary btn-lg" type="submit">send email</button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </section>
</body>
</html>

templates/accounts/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>signup</title>

    <!-- Bootstrap core CSS -->
    <link  rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >

    <!-- Custom styles for this template -->
    <link  rel="stylesheet"href="{% static 'css/signin.css' %}"  >
  </head>

  <body class="text-center">
 
    <form class="form-signin" method="POST" action=".">
      {% csrf_token %} 
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
     <label for="inputEmail" class="sr-only" data-validate="name is required">username </label>
      <input type="text" name='username' class="form-control" placeholder="username" required autofocus>
      <label for="inputEmail" class="sr-only">Email </label>
      <input type="email" name='email' class="form-control" placeholder="Email" required >
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password1" class="form-control" placeholder="Password" required>
      <label for="inputPassword" class="sr-only">Confirm Password</label>
      <input type="password" name="password2" class="form-control" placeholder="Confirm Password" required>
      <div class="checkbox mb-3">
        <label>
       <div class="col-12">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" name="remember_me" id="remember_me">
                      <label class="form-check-label text-secondary" for="remember_me">
                        Keep me logged in
                      </label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                      <button class="btn btn-primary btn-lg" type="submit">sign up</button>
                    </div>
                  </div>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>